import {
  Folder,
  Code2,
  Terminal,
  Globe,
  Smartphone,
  Server,
  Database,
  Bot,
  Gamepad2,
  Palette,
  Package,
  Puzzle,
  Cpu,
  Wrench,
  FileCode,
  LayoutDashboard,
  Blocks,
  Rocket,
  Layers,
  Boxes,
  Heart,
  Briefcase,
  GraduationCap,
  Sparkles,
  Star,
  Zap,
  Trophy,
  Target,
  Lightbulb,
  Music,
  Camera,
  Book,
  Coffee,
  Users,
  Award,
  LucideIcon,
} from 'lucide-react';

// Direct icon map for reliable lookups
const ICON_MAP: Record<string, LucideIcon> = {
  Folder,
  Code2,
  Terminal,
  Globe,
  Smartphone,
  Server,
  Database,
  Bot,
  Gamepad2,
  Palette,
  Package,
  Puzzle,
  Cpu,
  Wrench,
  FileCode,
  LayoutDashboard,
  Blocks,
  Rocket,
  Layers,
  Boxes,
  Heart,
  Briefcase,
  GraduationCap,
  Sparkles,
  Star,
  Zap,
  Trophy,
  Target,
  Lightbulb,
  Music,
  Camera,
  Book,
  Coffee,
  Users,
  Award,
};

// Get a Lucide icon component by name
export function getLucideIcon(name: string): LucideIcon | null {
  return ICON_MAP[name] || null;
}

// Common icons for sections
export const SECTION_ICONS = [
  { name: 'Code2', label: 'Code' },
  { name: 'Heart', label: 'Heart' },
  { name: 'Briefcase', label: 'Briefcase' },
  { name: 'GraduationCap', label: 'Graduation' },
  { name: 'Sparkles', label: 'Sparkles' },
  { name: 'Star', label: 'Star' },
  { name: 'Zap', label: 'Zap' },
  { name: 'Rocket', label: 'Rocket' },
  { name: 'Trophy', label: 'Trophy' },
  { name: 'Target', label: 'Target' },
  { name: 'Lightbulb', label: 'Lightbulb' },
  { name: 'Palette', label: 'Palette' },
  { name: 'Music', label: 'Music' },
  { name: 'Gamepad2', label: 'Gaming' },
  { name: 'Camera', label: 'Camera' },
  { name: 'Book', label: 'Book' },
  { name: 'Coffee', label: 'Coffee' },
  { name: 'Globe', label: 'Globe' },
  { name: 'Users', label: 'Users' },
  { name: 'Award', label: 'Award' },
] as const;

// Common icons for projects
export const PROJECT_ICONS = [
  { name: 'Folder', label: 'Folder' },
  { name: 'Code2', label: 'Code' },
  { name: 'Terminal', label: 'Terminal' },
  { name: 'Globe', label: 'Web' },
  { name: 'Smartphone', label: 'Mobile' },
  { name: 'Server', label: 'Server' },
  { name: 'Database', label: 'Database' },
  { name: 'Bot', label: 'Bot' },
  { name: 'Gamepad2', label: 'Game' },
  { name: 'Palette', label: 'Design' },
  { name: 'Package', label: 'Package' },
  { name: 'Puzzle', label: 'Plugin' },
  { name: 'Cpu', label: 'Hardware' },
  { name: 'Wrench', label: 'Tool' },
  { name: 'FileCode', label: 'Script' },
  { name: 'LayoutDashboard', label: 'Dashboard' },
  { name: 'Blocks', label: 'Blocks' },
  { name: 'Rocket', label: 'Startup' },
  { name: 'Layers', label: 'Layers' },
  { name: 'Boxes', label: 'Container' },
] as const;
